version: '3.3'
services:
  backend:
    image: ZekiCi/234project-backend:latest
    ports:
      - "9999:8080"
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "9998:80"
    volumes:
      - type: bind
        source ./dockerpath
        targe: /user/share/nginx/html/assets